# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 140)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background-color: rgb(25, 25, 25);\n"
"}\n"
"\n"
"QListView {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_prev = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_prev.setGeometry(QtCore.QRect(10, 10, 111, 50))
        self.btn_prev.setObjectName("btn_prev")
        self.btn_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(130, 10, 121, 50))
        self.btn_pause.setObjectName("btn_pause")
        self.btn_next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(259, 10, 111, 50))
        self.btn_next.setObjectName("btn_next")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 361, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lbl_nowPlaying = QtWidgets.QLabel(parent=self.frame)
        self.lbl_nowPlaying.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.lbl_nowPlaying.setObjectName("lbl_nowPlaying")
        self.lbl_trackName = QtWidgets.QLabel(parent=self.frame)
        self.lbl_trackName.setGeometry(QtCore.QRect(100, 10, 201, 21))
        self.lbl_trackName.setObjectName("lbl_trackName")
        self.pb_timeline = QtWidgets.QProgressBar(parent=self.frame)
        self.pb_timeline.setGeometry(QtCore.QRect(10, 30, 341, 23))
        self.pb_timeline.setProperty("value", 24)
        self.pb_timeline.setObjectName("pb_timeline")
        self.lbl_endTime = QtWidgets.QLabel(parent=self.frame)
        self.lbl_endTime.setGeometry(QtCore.QRect(310, 10, 41, 21))
        self.lbl_endTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_endTime.setObjectName("lbl_endTime")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_prev.setText(_translate("MainWindow", "perv"))
        self.btn_pause.setText(_translate("MainWindow", "play"))
        self.btn_next.setText(_translate("MainWindow", "next"))
        self.lbl_nowPlaying.setText(_translate("MainWindow", "Now playing:"))
        self.lbl_trackName.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_endTime.setText(_translate("MainWindow", "00:00"))
